[camera]
focus = 0.0
zoom = 1.0
flip_mode = 3
;0 No flip
;1 Horizontal flip
;2 Vertical flip
;3 180 rotation

[focus_controller]
x_start = 1
x_end = 161
prior_range = 10, 70

[logger]
log_level = DEBUG
console_log_level = INFO